---
- name: "Log in to openshift cluster with token: {{ ocp_url }}"
  #command: "oc login -u '{{ ocp_user }}' -p '{{ ocp_password }}' --insecure-skip-tls-verify='{{ ocp_login_skip_tls_verify | default('false') }}' '{{ ocp_url }}'"
  #command: "oc login {{ --token='${{ ocp_token }}' if ocp_token is defined else '-u'.join(('{{ ocp_user }}' -p '{{ ocp_password }}' }} --insecure-skip-tls-verify='{{ ocp_login_skip_tls_verify | default('false') }}' '{{ ocp_url }}'"
  #command: "oc login -u '{{ ocp_user }}' -p '{{ ocp_password }}' --insecure-skip-tls-verify='{{ ocp_login_skip_tls_verify | default('false') }}' '{{ ocp_url }}'"
  debug:
    msg: "{{ '--token=' }}"
  when: ocp_token is defined

#- name: "Log in to openshift cluster with username / password: {{ ocp_url}}"
  #debug:
    #msg: "{{ 'no token' }}"
    #when: ocp_token is undefined
