---
- debug:
    msg: "--token"
    msg: "oc login --token '{{ ocp_token }}' --insecure-skip-tls-verify='{{ ocp_login_skip_tls_verify | default('false') }}' '{{ ocp_url }}'"
  when: ocp_token is defined
- debug:
    msg: "oc login -u '{{ ocp_user }}' -p '{{ ocp_password }}' --insecure-skip-tls-verify='{{ ocp_login_skip_tls_verify | default('false') }}' '{{ ocp_url }}'"
  when: ocp_token is undefined
