---
- name: "Log in to openshift cluster: {{ ocp_url}}"
  command: "oc login -u '{{ ocp_user }}' -p '{{ ocp_password }}' --insecure-skip-tls-verify='{{ ocp_login_skip_tls_verify | default('false') }}' '{{ ocp_url }}'"
